### ISSUE TITLE
Token handling

### ISSUE THREAD

**Issue by sckott** [getwilds/proofr#11]
- Dont set as env var by deafult anymore when running auth function
- Allow for passing in token as param

to support shiny flow

**Comment by dtenenba** [comment]
> Allow for passing in token as param

Make sure this is done via a POST or PUT and not a GET request, so tokens don't end up in logs.

**Comment by sckott** [comment]
Thx for the note. 

When I say parameter here I'm referring to function parameter. 

Internally the token is only being passed in the request as a header 

This issue is about making the shiny flow easier. Setting tokens as env vars is great for individual users in their own r instance but not with multiple users as you have seen with the dev app
