### ISSUE TITLE
dependency on rstudioapi

### ISSUE THREAD

**Issue by vortexing** [getwilds/proofr#16]
Followed instructions, `rstudioapi` did not get installed correctly as a dependency. 

```
> pak::pak("getwilds/proofr:v0.2")
Error in loadNamespace(x) : there is no package called ‘rstudioapi’
```

`> sessionInfo()
R version 4.4.0 (2024-04-24)
Platform: x86_64-apple-darwin20
Running under: macOS Sonoma 14.4.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.4.0    R6_2.5.1          fastmap_1.1.1     cli_3.6.2         htmltools_0.5.8.1
 [6] tools_4.4.0       rstudioapi_0.16.0 yaml_2.3.8        rmarkdown_2.26    knitr_1.46       
[11] xfun_0.43         digest_0.6.35     rlang_1.1.3       pak_0.7.2         evaluate_0.23  `

**Comment by dtenenba** [comment]
It doesn't look like proofr has a dependency on rstudioapi, but pak has a Suggests dependency on it, so I am puzzled by this. I tried it myself and got:

```
> pak::pak("getwilds/proofr:v0.2")
Error:
! error in pak subprocess
Caused by error:
! Could not solve package dependencies:
* getwilds/proofr:v0.2: ! pkgdepends resolution error for getwilds/proofr:v0.2.
Caused by error:
! Can't find GitHub repo getwilds/proofr:v0.2.
Type .Last.error to see the more details.
> .Last.error
<callr_error/rlib_error_3_0/rlib_error/error>
Error:
! error in pak subprocess
Caused by error:
! Could not solve package dependencies:
* getwilds/proofr:v0.2: ! pkgdepends resolution error for getwilds/proofr:v0.2.
Caused by error:
! Can't find GitHub repo getwilds/proofr:v0.2.
---
Backtrace:
1. pak::pak("getwilds/proofr:v0.2")
2. pak::pkg_install(pkg, ...)
3. pak:::remote(function(...) get("pkg_install_make_plan", asNamespace("pak"))(...)…
4. err$throw(res$error)
---
Subprocess backtrace:
1. base::withCallingHandlers(cli_message = function(msg) { …
2. get("pkg_install_make_plan", asNamespace("pak"))(...)
3. prop$stop_for_solution_error()
4. private$plan$stop_for_solve_error()
5. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
6. base::throw(new_error("Could not solve package dependencies:\n", msg, …
7. | base::signalCondition(cond)
8. global (function (e) …
>

```

If I just do `pak::pak("getwilds/proofr")` it works.

**Comment by dtenenba** [comment]
Try starting R with `--vanilla` and see if you get the same thing.

**Comment by vortexing** [comment]
what a mess.  consider alternative: ` remotes::install_github("getwilds/proofr@v0.2")`

**Comment by vortexing** [comment]
@seankross maybe change the readme to something simpler that works reliably?

**Comment by tefirman** [comment]
@sckott @seankross -- Do either of you have a strong opinion between `pak::pak` and `remotes::install_github` as the preferred method of installation? If you prefer `pak::pak`, probably at least worth adding another snippet in the "Installation" section of the README stating something like:

You can install previous versions of proofr with:
```
remotes::install_github("getwilds/proofr@v0.1")
```

**Comment by dtenenba** [comment]
Have we solved the problem at the top of this issue? If not, I'd suggest recommending `remotes` as the installation method.
In addition, IMO people are more likely to have `remotes` installed so they won't have to install something to install something.

**Comment by sckott** [comment]
A couple things here:

- Note the syntax for installing a branch or tag is `@` instead of `:` (as mentioned by Taylor) - so that's the real problem at the root of amy's issue here, not which package is used to install packages
- here's what posit says about `remotes` vs. `pak` https://solutions.posit.co/envs-pkgs/environments/installation/ 
  - thusly, `pak` has a much nicer experience for humans, where the installation log is suppressed, and there's only 2 imports vs. 0 for `remotes`, but they are both base R packages
- you might be right dan that more people have `remotes`, but I think it makes sense to push users in the direction of a nicer installation experience

Having said all that if most people want `remotes`, i'm fine with that

**Comment by seankross** [comment]
My preference is to instruct people to use `pak`. When communicating with end users `pak` makes it easier to understand their underlying problem.

**Comment by sckott** [comment]
closing - we can reopen if folks want to discuss further, change anything
