### ISSUE TITLE
Add guidance for connecting to Shiny-created server

### ISSUE THREAD

**Issue by vortexing** [getwilds/proofr#20]
... via the shiny app, can we provide some guidance about how to then connect to that server via proofr in R? Do we need to make a new server via proofr?  Can you get your token from the app?  I'd hope not, right?

**Comment by dtenenba** [comment]
`token <- proof_authenticate(username, password)` will give you your token, then
`proof_status(token=token)$cromwellUrl` will return the proof server URL.

**Comment by tefirman** [comment]
The more I think about this, I don't think we need this guidance for two reasons:

1. I don't envision a ton of cross-platform usage, feels like most users will either use the command line or the GUI, but not both.
2. Even if someone does this, the `proof_start` function still won't allow them to create another server, it just returns `Error: Conflict (HTTP 409) Job is already running`. At that point, it feels logical for them to go to `proof_status` to identify the existing server's details.
 
Closing this for now, but can definitely reopen if people disagree.
