### ISSUE TITLE
documentation small thing - pak::pak("rcromwell")

### ISSUE THREAD

**Issue by jayoung** [getwilds/proofr#22]
hi,

finally started testing PROOF

on this page:  https://getwilds.org/proofr/articles/proofr.html#rcromwell-setup

there's a chunk that looks like this
```
if (!requireNamespace("rcromwell", quietly=TRUE)) {
  install.packages("pak")
  pak::pak("rcromwell")
}
```

The line `pak::pak("rcromwell")` should read `pak::pak("getwilds/rcromwell")`

Testing more now...

thanks!

Janet

**Comment by sckott** [comment]
Thanks @jayoung fixing now!
