### ISSUE TITLE
rstudio-server and the PROOF_TOKEN env

### ISSUE THREAD

**Issue by jayoung** [getwilds/proofr#23]
hi there,

documentation suggestion - I'm actually unclear on whether proofr is intended to be a Hutch-focussed resource or more general, so maybe this comment is too specific.

But the docs caused me brief confusion yesterday, until Dan cleared it up for me on Slack.

[This section](https://getwilds.org/proofr/articles/proofr.html#authenticate-with-the-proof-api) tells me about setting PROOF_TOKEN as an environmental variable.   But when running our Hutch Rstudio-server, R doesn't preserve most environmental variables from my generic login shell when it starts an R session, so the suggested method wasn't working. 

I had to set the token manually, until I got this advice from Dan:
"You can create a ~/.Renviron file that contains PROOF_TOKEN=your-token-here and it will be available in your RStudio Server session. For the sake of security, be sure and run chmod 0400 ~/.Renviron just to make sure only you can see its contents."

Might be good to include that advice in the proofr documentation?

thanks,

Janet

**Comment by sckott** [comment]
Thanks for this issue @jayoung 

>  I'm actually unclear on whether proofr is intended to be a Hutch-focussed resource or more general, so maybe this comment is too specific.

For now it's specific to Hutch, but AFAIK we intend the PROOF API to be an open source product later and then this would be a client one could use to interact with it. 

Thanks for the tip, I'll include something along those lines in the vignette
